### ISSUE TITLE
Incorrect WiFi password

### ISSUE THREAD

**Issue by BrynM** [thenickdude/steal-chads-password#1]
I hear Chad may be rotating passwords. We need an investigative team to discover the new QR code and break the new password. Is there any way we could maybe get some kind of monitoring installed on Chad's coffee table?

**Comment by ThisIsJeron** [comment]
might be a lot harder now that chad's deleted his reddit account

**Comment by ingochris** [comment]
Chad's left index print was leaked. We might be able to pivot from that vector.

**Comment by ThisIsJeron** [comment]
brute force all fingerprint enabled smartphones and see if any of them unlock

**Comment by BrynM** [comment]
I've given up on Chad and am now trying to break Steve's wifi. Closing this issue as Chad is no longer relevant.
