### ISSUE TITLE
You doxxed Chad

### ISSUE THREAD

**Issue by shawwn** [thenickdude/steal-chads-password#2]
https://www.reddit.com/r/3Dprinting/comments/7ibqn3/made_a_qr_code_coaster_for_when_i_have_guest_and/dqyu1au/

His full password contains his first and last name, which is enough to look up some sensitive information about him. Reddit being Reddit, they couldn't resist pointing this out and have started to spread it around.

It may be a good idea to remove the full password from your edit.

**Comment by thenickdude** [comment]
Googling his username also reveals his first and last name, in the very first search result. He's not trying to keep his name a secret.

**Comment by shawwn** [comment]
Actually, he deleted his Reddit post. Most people can't see his Reddit username. I'm pretty sure he's worried:

![image](https://user-images.githubusercontent.com/59632/33787069-3f454846-dc31-11e7-96ff-1542eea0085e.png)

Would you mind respecting his privacy by removing his personal information from Reddit, as per the site guidelines?

**Comment by thenickdude** [comment]
His personal information is contained within the image he posted, which has already been viewed over 640,000 times. There's no taking that back.

Also, his username is posted within the thread anyway.

**Comment by shawwn** [comment]
Apparently you noticed 7 hours ago that he deleted his Reddit account:

![image](https://user-images.githubusercontent.com/59632/33787188-c1194ac0-dc31-11e7-95cf-fbb88d7a5493.png)

You can do whatever you want, but why not empathize a little?

I searched for his username and couldn't find anything. You're right, though: it's posted as a 2-point reply, which there's no need to link to here, and which the vast majority of people won't see.

This post will be archived soon, and crawlers will be taking various snapshots of the info. You still have a chance to minimize the long-term spread of this information.

You saw how sensitive the info is, as per my original link. And for whatever it's worth, it's against the site's terms of service to post the first and last name of any of its users.

I know you had good intentions, and I'm not trying to force you to do anything. I'm just asking you to reconsider. As technologists, we have a responsibility to watch out for laypeople, especially when they do something stupid.

(Are you sure you see nothing worrying about someone's first and last name being posted right next to their criminal record, which normally people don't look up?)

**Comment by thenickdude** [comment]
>I searched for his username and couldn't find anything. 

Really? I don't believe that my Google search results are that personalised. I'm emailing you a screenshot. You can see that he already has public profiles on other sites with the same username and his full name published: He obviously doesn't give a shit about publishing it. That would be like me setting my username to nsherlock and complaining that people discovered that my full name is Nick Sherlock: No shit, Sherlock!

>This post will be archived soon, and crawlers will be taking various snapshots of the info. You still have a chance to minimize the long-term spread of this information.

It's pointless to do anything when the QR code with his information in it is sitting right there on Imgur for anybody to see, as well as everybody that has seen it already. The amount of missing data in the QR code is absolutely trivial to recover.

>(Are you sure you see nothing worrying about someone's first and last name being posted right next to their criminal record, which normally people don't look up?)

Wat. You could say the same about every entry in the phonebook. And the phonebook even gives you their physical address!

**Comment by shawwn** [comment]
Sorry, I was imprecise.

I meant to say, I searched the Reddit thread for references to his username. Other than the one you linked here, it's very hard for anyone to find it. That means it's hard to know who this post is about -- "Chad" is all they have to go on.

Until they see your edit, and immediately see their first and last name.

And now when people search that person's first and last name, there is a high probability of leading them straight to that reddit thread, where their criminal record is posted as a reply.

I don't know about you, but that would freak me enough out to delete my Reddit account too. And that would be a major bummer, because I have a lot of fond memories of that account.

Listen, I'm not trying to say you did anything wrong. I'm just trying to shed some light on the other side of it.

You're correct that the information is technically in the QR code, just like his last name is technically in the comments. But both the comment and the QR code are concealed from most people who happen to arrive at that page. You posted their first and last name prominently at the very top. There's quite a big difference.

But again, it's ultimately up to you, so...  Anything you want to do is fine.

**Comment by shawwn** [comment]
(The probability of searching their first and last name leading to that Reddit page will only increase with time unless you remove your edit, too. So it really is up to you.)

**Comment by shawwn** [comment]
Just to demonstrate, searching "/u/c" gives no results

![image](https://user-images.githubusercontent.com/59632/33787940-2c742ff8-dc35-11e7-89f5-22bca6e67d43.png)

Even navigating to your reply shows nothing:

![image](https://user-images.githubusercontent.com/59632/33787977-53060682-dc35-11e7-9f5e-77137c7be600.png)

**Comment by shawwn** [comment]
Kudos! Thanks for that.
